full_name = "Peter Richter"
description = "Born in Belgium, from German/Dutch descent, Peter is a German citizen with a 25+ year background in Logistics & Supply Chain, of which the last 15 years managing the Supply Chain for Ferrero Russia. 
In 09/2010 left Ferrero – Appointed Business Development Director at Swiss based DEGA AG - sphere: Industrial Park Development & Decentralised Energy
In 04/2014 – Divested 67% of Dega’s 30MW CHP Plant to E.ON Connecting Energies
In 11/2014 – Appointed GM at E.ON Connecting Energies Russia – sphere:B2B Decentralised Energy 
In 02/2016 – Became self employed project integration / management consultant –sphere: primarily Industrial Development & Construction and Decentralised Energy  
In 07/2019 – Joined the Business Development Team of Threefold Tech – part-time – sphere IT infrastructure  
In 08/2019 – Appointed GM at Kadeon Development – part-time – sphere: Industrial Construction 
Peter is the Chairman of the Expert Council at the Chamber of Commerce & Industry of Odintsovo (RF), Member of the Expert Council at the Strategy Foundation, as well as an Ambassador at the Threefold Foundation.
"
why_threefold = "Threefold is simply an amazing ecosystem based on cutting edge & disruptive software technology that unites amazing people, a fantastic business model and an incredible social impact potential, hopefully making the world a better place for generations to come"
function = "Business Development"
rank = 0
project_ids = [0]
contribution_ids = [0]
nationality = "German / Dutch"
